<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>DtoB</AssemblyName>
    <Version>0.2.0</Version>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../../packages/DtoB.Ipc/DtoB.Ipc.csproj" /><ProjectReference Include="../../packages/DtoB.Project/DtoB.Project.csproj" /></ItemGroup>
</Project>
